### ISSUE TITLE
Error encountered while sending email 

### ISSUE THREAD

**Issue by imbinit17** [GitAccSK/code-tech-gyan#1]
![image](https://user-images.githubusercontent.com/101280000/167259929-9225d561-fa6d-43b7-b56a-b57b72ff2bb2.png)

This is the error encountered ,I don;t know where it's causing it . 
The only change I made was the receipent adress , sender adress and password (rest the code is same as https://github.com/GitAccSK/code-tech-gyan/blob/main/Send%20email%20using%20java)

I have imported the folowing jar's :- 
1. smtp
2. activation
3. javax.mail 

Less Secure App Access is given .Google though is suspending the facility(less-secure-app-access) from 30th May but it should work as of now .Though the SMTP is working for my Python code which is available here at my github .You can have a look at it (https://github.com/imbinit17/Student-Result-Mailer/blob/main/sendEmail.py)

If you have any idea by what means it can be corrected ,please let me know .
Thank You .

**Comment by Burgermench** [comment]
Try the port 587 instead.
Good luck!

**Comment by GitAccSK** [comment]
Hi Binit,

Could you try port 587 instead of 547 . Let me know if you are still stuck with the code. 

Thanks,
Surabhi

**Comment by imbinit17** [comment]
Sorry to say but I am out on vacations and I don't have access to my files or even my laptop . Once I will be back by 20th ,I will sure try it out as early as possible and let you know of the same .

Thanks for being so kind and patient

**Comment by imbinit17** [comment]
Hi Surabhi ,
Just trying out with the code and I changed the port from 547 to 587 as mentioned by you .The port error got fixed by it but there was a new error encountered and it said "Bad Credentials " though what I entered was correct . After searching the internet for it ,I came to know that it can be resolved just by turning on 2 step verification and generating an app password that just resolves the issue {wrote this incase anyone else may get benefitted from this } .

After the app password thing , a new error was caused that I am unable to fix by any means and thus sought for your help .Basically I am not into this but just want to use this {emailer} for my next project as a tool .

The error is caused at MimeBodyPart setContent at the html/text ....

As far I can guess the code written by you might have worked until Google turned off "less secure app access" ,and thus that's what may be causing the error .

It would be very nice of you if you could just see to your code whether it is compatible as of today .

Waiting for your reply .
Thank You ! 

![image](https://user-images.githubusercontent.com/101280000/197383439-4193fe92-0486-435d-b239-5679ff2fe228.png)

**Comment by imbinit17** [comment]
Found out the error .

Basically earlier authentication wasn't a must as google allowed less secure app access . 
After they removed it ,
1. one has to enable 2FA and app password for the smtp server (gmail SMTP)
2. Also when creating sessions object , auth was set to null ....which should have a authentication necessarily otherwise it would come up with the AuthenticationFailedExcepetion

So , made a pull request with the changes (didn't feel like altering the files itself , so put the original files in folder named utilities  as the program itself said "package utilities" and wrote a whole new program with the old mechanisms and some changes with the very noticeable one having a Auth enabled)......

Pull Request
https://github.com/GitAccSK/code-tech-gyan/pull/2

**Comment by imbinit17** [comment]
Closing the issue
